# Generated by Django 5.2.5 on 2025-09-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databaseForRecords", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExercisesFromAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("gif_url", models.URLField()),
                ("target_muscles", models.JSONField()),
                ("body_parts", models.JSONField()),
                ("equipments", models.JSONField()),
                ("secondary_muscles", models.JSONField()),
                ("instructions", models.JSONField()),
            ],
        ),
    ]
